sonar.projectKey=ms-products
sonar.projectName=Microservicio de Productos
sonar.host.url=http://localhost:9000
sonar.login=Microservicio de Productos

sonar.sources=src
sonar.language=java
sonar.java.binaries=target
